name: Deploy to Ubuntu Server

on:
  push:
    branches: [ master ]  # or main, if you're using main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "✅ Connected to server"
          cd /home/ubuntu  # change this to your project path
          git pull origin master     # update the code
